### ISSUE TITLE
Python error when loading: AttributeError: 'NoneType' object has no attribute 'getIcon'

### ISSUE THREAD

**Issue by AlisterH** [Mi-Kbs-gis/TlugProcessing#4]
Hi, this plugin fails to load and prevents the processing settings dialog from opening.
Python errors:
````
2018-02-26T11:11:25	1	Traceback (most recent call last):
			  File "C:/OSGEO4~1/apps/qgis-ltr/./python/plugins\processing\ProcessingPlugin.py", line 175, in openConfig
			    dlg = ConfigDialog(self.toolbox)
			  File "C:/OSGEO4~1/apps/qgis-ltr/./python/plugins\processing\gui\ConfigDialog.py", line 91, in __init__
			    self.fillTree()
			  File "C:/OSGEO4~1/apps/qgis-ltr/./python/plugins\processing\gui\ConfigDialog.py", line 120, in fillTree
			    self.fillTreeUsingProviders()
			  File "C:/OSGEO4~1/apps/qgis-ltr/./python/plugins\processing\gui\ConfigDialog.py", line 216, in fillTreeUsingProviders
			    icon = provider.getIcon()
			  File "C:/Users/alistair/.qgis2/python/plugins\TlugProcessing\tlug_algorithms_provider.py", line 103, in getIcon
			    """We return the default icon.
			AttributeError: 'NoneType' object has no attribute 'getIcon'
			
2018-02-26T11:11:43	1	Traceback (most recent call last):
			  File "C:/OSGEO4~1/apps/qgis-ltr/./python/plugins\processing\gui\ProcessingToolbox.py", line 75, in openSettings
			    dlg = ConfigDialog(self)
			  File "C:/OSGEO4~1/apps/qgis-ltr/./python/plugins\processing\gui\ConfigDialog.py", line 91, in __init__
			    self.fillTree()
			  File "C:/OSGEO4~1/apps/qgis-ltr/./python/plugins\processing\gui\ConfigDialog.py", line 120, in fillTree
			    self.fillTreeUsingProviders()
			  File "C:/OSGEO4~1/apps/qgis-ltr/./python/plugins\processing\gui\ConfigDialog.py", line 216, in fillTreeUsingProviders
			    icon = provider.getIcon()
			  File "C:/Users/alistair/.qgis2/python/plugins\TlugProcessing\tlug_algorithms_provider.py", line 103, in getIcon
			    """We return the default icon.
			AttributeError: 'NoneType' object has no attribute 'getIcon'
			
2018-02-26T11:14:08	1	Traceback (most recent call last):
			  File "C:/OSGEO4~1/apps/qgis-ltr/./python/plugins\processing\gui\ProcessingToolbox.py", line 75, in openSettings
			    dlg = ConfigDialog(self)
			  File "C:/OSGEO4~1/apps/qgis-ltr/./python/plugins\processing\gui\ConfigDialog.py", line 91, in __init__
			    self.fillTree()
			  File "C:/OSGEO4~1/apps/qgis-ltr/./python/plugins\processing\gui\ConfigDialog.py", line 120, in fillTree
			    self.fillTreeUsingProviders()
			  File "C:/OSGEO4~1/apps/qgis-ltr/./python/plugins\processing\gui\ConfigDialog.py", line 216, in fillTreeUsingProviders
			    icon = provider.getIcon()
			  File "C:/Users/alistair/.qgis2/python/plugins\TlugProcessing\tlug_algorithms_provider.py", line 103, in getIcon
			    """We return the default icon.
			AttributeError: 'NoneType' object has no attribute 'getIcon'
			
2018-02-26T11:14:25	1	Traceback (most recent call last):
			  File "C:/OSGEO4~1/apps/qgis-ltr/./python/plugins\processing\gui\ProcessingToolbox.py", line 75, in openSettings
			    dlg = ConfigDialog(self)
			  File "C:/OSGEO4~1/apps/qgis-ltr/./python/plugins\processing\gui\ConfigDialog.py", line 91, in __init__
			    self.fillTree()
			  File "C:/OSGEO4~1/apps/qgis-ltr/./python/plugins\processing\gui\ConfigDialog.py", line 120, in fillTree
			    self.fillTreeUsingProviders()
			  File "C:/OSGEO4~1/apps/qgis-ltr/./python/plugins\processing\gui\ConfigDialog.py", line 216, in fillTreeUsingProviders
			    icon = provider.getIcon()
			  File "C:/Users/alistair/.qgis2/python/plugins\TlugProcessing\tlug_algorithms_provider.py", line 103, in getIcon
			    """We return the default icon.
			AttributeError: 'NoneType' object has no attribute 'getIcon'

**Comment by Mi-Kbs-gis** [comment]
already solved
